<?php $direct = Mage::getModel('cardsaveonlinepayments/direct'); ?>
<?php $_code = $this->getMethodCode(); ?>
<?php $route = $this->getRequest()->getRequestedRouteName(); if($route == 'onestepcheckout'){ $fieldCode = '['.$_code.']'; } else { $fieldCode = ''; }?>

<?php if ($direct->getConfigData('mode') == Cardsave_Cardsaveonlinepayments_Model_Source_PaymentMode::PAYMENT_MODE_HOSTED_PAYMENT_FORM) {?>
	<fieldset class="form-list">
		<ul id="payment_form_<?php echo $_code ?>" style="display:none">
			<li>
				<img alt="<?php echo $this->__('CardSave Online Payment Logo'); ?>" src="<?php echo $this->getSkinUrl('images/cardsave_online.png'); ?>">
			</li>
	        <li>
	            <?php echo $this->__('You will be redirected to a secure page where you can complete your payment.') ?>
	        </li>
	        <li class='notice-msg'>
	        	<?php echo $this->__('Do not attempt to click the "BACK" button in your browser once you have been redirected to the secure payment page to complete your payment. If you need make changes your order, please do so before confirming your order.') ?>
	        </li>
	    </ul>
	</fieldset>
<?php } else {?>
	<fieldset class="form-list">
	    <ul id="payment_form_<?php echo $_code; ?>" style="display:none">
	    	<li>
				<img alt="<?php echo $this->__('CardSave Online Payment Logo'); ?>" src="<?php echo $this->getSkinUrl('images/cardsave_online.png'); ?>">
			</li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_owner"><?php echo $this->__('Name On Card') ?> <span class="required">*</span></label><br/>
	                <input type="text" title="<?php echo $this->__('Name On Card') ?>" class="input-text required-entry validate-length maximum-length-100" id="<?php echo $_code; ?>_cc_owner" name="payment<?php echo $fieldCode; ?>[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_number"><?php echo $this->__('Card Number') ?> <span class="required">*</span></label><br/>
	                <input type="text" id="<?php echo $_code; ?>_cc_number" name="payment<?php echo $fieldCode; ?>[cc_number]" title="<?php echo $this->__('Card Number') ?>" class="input-text required-entry validate-digits validate-length maximum-length-20 validate-cc-number" value=""/>
	            </div>
	        </li>
	        <li>
	         	<label for="<?php echo $_code; ?>_expiration"><?php echo $this->__('Expiry Date') ?> <span class="required">*</span></label><br/>
	         	<div class="input-box">
	                <div class="v-fix">
	                <select id="<?php echo $_code; ?>_expiration" name="payment<?php echo $fieldCode; ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
	                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
	                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	                
	                <div class="v-fix">
	                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
	                <select id="<?php echo $_code; ?>_expiration_yr" name="payment<?php echo $fieldCode; ?>[cc_exp_year]" class="year required-entry">
	                <?php foreach ($this->getCcYears() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_ss_issue"><?php echo $this->__('Issue Number') ?></label><br />
	                <div class="v-fix"><input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-digits validate-length maximum-length-2" id="<?php echo $_code ?>_cc_ss_issue" name="payment<?php echo $fieldCode; ?>[cc_ss_issue]" style="width:50px;" value="" /></div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_cid"><?php echo $this->__('CV2') ?> <span class="required">*</span></label><br/>
	                <div class="v-fix"><input type="text" title="<?php echo $this->__('CV2') ?>" class="input-text required-entry validate-digits validate-length maximum-length-4" id="<?php echo $_code; ?>_cc_cid" name="payment<?php echo $fieldCode; ?>[cc_cid]" style="width:50px;" value=""/></div>
	                &nbsp;
	                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
	            </div>
	        </li>
	    </ul>
	</fieldset>
<?php }?>